### ISSUE TITLE
[Setting] 모듈 통합해서 돌리는 플러그인 추가

### ISSUE THREAD

**Issue by jiaekim123** [pmc-web/market-consumer#30]

**Comment by SSONG22** [comment]
https://gaemi606.tistory.com/entry/IntelliJ%EC%97%90%EC%84%9C-%EC%97%AC%EB%9F%AC-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EB%8F%99%EC%8B%9C%EC%97%90-Run%ED%95%98%EA%B8%B0
