### ISSUE TITLE
[Search] 01-7~9.Search 화면 api

### ISSUE THREAD

**Issue by SSONG22** [pmc-web/market-consumer#55]
* 01-7 : 인기검색어 리스트 (max : n개)
* 01-8 : 검색어로 나오는 product list
*  카테고리 : 가격대, 카테고리, 색상(!!!!) 별 (product) 조회 
* 01-9 : 검색어로 나오는 shop list

**Comment by jiaekim123** [comment]
색상은.. 에반데...
